general:
  t_max: 200
  num_batches: 1 # Number of simultaneously simulated batches

parameters:
  production_specific:
    # ACE specific parameters
    prtp: 0.013896                  # Pure rate of social time preference, Global
    xi_0: 0.2219
    #xi_1: 0.25                     # Baked into the tau. probably not needed.
    kappa: 0.3
    delta_k: 0.44
    g_k: 0.29                       # Assumed to be the same as g_kt

    # DICE Production specific parameters
    timestep: 5
    
    ## For carbon intensity sigma_t
    g_0_sigma: -0.0152
    delta_sigma: 0.001
    sigma_0: 0.00009556
    delta_t: 5
    
    ## For abatement costs theta_{1,t}
    p_back: 0.55
    g_back: 0.005
    theta_2: 2.6
    c2co2: 3.666
    
    ## For initializing labor (N_t)
    pop0: 7403                      # Initial world population 2015 (millions)
    popadj: 0.134                   # Growth rate to calibrate to 2050 pop projection
    popasym: 11500                  # Asymptotic population (millions)
    
    ## For initializing total factor productivity
    dela: 0.005                     # Decline rate of TFP per 5 years
    ga0: 0.076                      # Initial growth rate for TFP per 5 years
    a0: 5.115                       # Initial level of total factor productivity

  climate_specific:
    sigma_forc: 0.5198
    M_pre: 596.4                    # Pre-industrial atmospheric carbon concentration ACE
    # M_pre: 600                    # Pre-industrial atmospheric carbon concentration DICE?
    
    Phi:
      - [0.8240, 0.0767, 0]
      - [0.1760, 0.9183, 0.0007]
      - [0, 0.0050, 0.9993]

    sigma_transition:
      - [0.166726698937639, 0.313477283382278]
      - [0.0229478090365842, 0.977052190963416]

# STATE VARIABLES
state_variables:
  - name: k_t
    init_val: 2.4698                # Log initial capital stock calibrated (1012 2019 USD) from dice
  - name: M_1_t
    init_val: 862.86                # 2015 Carbon stock Atmosphere
  - name: M_2_t
    init_val: 1541.11               # 2015 Carbon stock Upper ocean
  - name: M_3_t
    init_val: 10010.44              # 2015 Carbon stock Lower ocean
  - name: tau_1_t
    init_val: 1.256727218547292     # Row 1, column 5 in initial temperatures, ace code
  - name: tau_2_t
    init_val: 1.185465055669960     # Row 2, column 5 in initial temperatures, ace code
  - name: t
    init_val: 0

# ACTIONS VARIABLES AND ACTIVATION FUNCTIONS
action_variables:
  # Controls
  - name: x_t
    activation: sigmoid
  - name: E_t
    activation: softplus
  # Value function prediction
  - name: V_t
    activation: softplus
  # Lagrange multipliers
  - name: lambda_k_t
    activation: linear
  - name: lambda_m_1
    activation: linear
  - name: lambda_m_2
    activation: linear
  - name: lambda_m_3
    activation: linear
  - name: lambda_tau_1
    activation: linear
  - name: lambda_tau_2
    activation: linear
  - name: lambda_t_BAU
    activation: softplus
  - name: lambda_E_t
    activation: softplus