parameters:
  production_specific:
    # ACE specific parameters
    xi_0: 0.2219
    #xi_1: 0.25 # Baked int the tau. probably not needed.
    kappa: 0.3
    delta_k: 0.44
    g_k: 0.29

    # DICE Production specific parameters
    ## For carbon intensity
    g_0_sigma: -0.0152
    delta_sigma: 0.001
    sigma_0: 0.00009556
    delta_t: 5
    ## For abatement costs
    p_0_back: 0.55
    g_back: 0.005
    theta_2: 2.6
    c2co2: 3.666

  climate_specific:
    sigma_forc: 0.5198
    M_pre: 596.4 # Pre-industrial atmospheric carbon concentration ACE
    # M_pre: 600 # Pre-industrial atmospheric carbon concentration DICE?
    
    Phi:
      - [0.8240, 0.0767, 0]
      - [0.1760, 0.9183, 0.0007]
      - [0, 0.0050, 0.9993]

    sigma:
      - [0.166726698937639, 0.313477283382278]
      - [0.0229478090365842, 0.977052190963416]

# STATE VARIABLES
state_variables:
  - name: k_t
    init_val: 10
  - name: M_1_t
    init_val: 862.86 # 2015 Carbon stock
  - name: M_2_t
    init_val: 1541.11 # 2015 Carbon stock
  - name: M_3_t
    init_val: 10010.44 # 2015 Carbon stock
  - name: tau_1_t
    init_val: 1
  - name: tau_2_t
    init_val: 1
  - name: t
    init_val: 1

# ACTIONS VARIABLES AND ACTIVATION FUNCTIONS
action_variables:
  # Controls
  - name: x_t
    activation: tf.keras.activations.linear
  - name: E_t
    activation: tf.keras.activations.linear
  # Value function prediction
  - name: V_t
    activation: tf.keras.activations.linear
  # Lagrange multipliers
  - name: lambda_k_t
    activation: tf.keras.activations.linear
  - name: lambda_m_1
    activation: tf.keras.activations.linear
  - name: lambda_m_2
    activation: tf.keras.activations.linear
  - name: lambda_m_3
    activation: tf.keras.activations.linear
  - name: lambda_tau_1
    activation: tf.keras.activations.linear
  - name: lambda_tau_2
    activation: tf.keras.activations.linear