hidden_nodes: 1024
hidden_activation_function: relu
output_activation_function: linear

# Variance scaling for initializing the neural network
kernel:
  mode: fan_avg
  distribution: uniform
  scale: 1.0
  seed: 1
